---
title: ""
output:
  html_document:
    include:
      after_body: "footer.html"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<html>
<title>Researc</title>
</html>

#### __PhD project__

In my PhD, I study language learning as the process of statistical learning over the input data. Some of the central questions I address are: are language learners sensitive to the statistical properties of the input they receive? can learners use this information to make correct generalizations? what is the exact nature of the learning mechanism that underpins this process? To answer these questions, I generate predictions using computational modelling, and then test these predictions with human participants using [artificial language learning experiments](https://www.sciencedirect.com/science/article/pii/S1364661300014674?via%3Dihub). I often collect data on-line, and [here](https://gorilla.sc/spotlight/masavujovic) you can read an interview I gave to Gorilla, a platform for hosting on-line experiments, about my work.

##### __Peer-reviewed conference talks and posters__

* __Vujović, M.__, Ramscar, M., \& Wonnacott, E. (2018). The role of prediction error in linguistic generalization and item-based learning. [Poster](files/vujovic_discriminationlearning.pdf) presented at:
    + Architectures and Mechanisms of Language Processing. Berlin, Germany.
    + Learning Language in Humans and Machines. Paris, France (also presented as a 2-minute highlight talk).
    + 1st International Workshop on Predictive Processing. San Sebastian, Spain. 
* Wonnacott, E., __Vujović, M.__, \& Miller, C. (2018). The role of variability in linguistic generalization: a computerized training study with 7-year-olds. Poster presented at:
    + Architectures and Mechanisms of Language Processing. Berlin, Germany.
    + Learning Language in Humans and Machines. Paris, France.
    + 1st International Workshop on Predictive Processing. San Sebastian, Spain. 
* __Vujović, M.__, Ramscar, M., \& Wonnacott, E. (2017). Discrimination learning, suffixing, and prefixing in an artificial language learning experiment. [Poster](files/bilbao_poster_final.pdf) presented at Interdisciplinary advances in Statistical learning. Bilbao, Spain. 
* __Vujović, M.__, Vigliocco, G., \& Wonnacott, E. (2017). Word order biases in adults and children: a silent gesture experiment. [Talk](files/vujovic_ubl_jerusalem_04-07-20171.pdf) presented at The 3rd Usage-Based Linguistics Conference. Jerusalem, Israel. 

